version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ${DOCKER_USERNAME:-yourname}/yii2-app:${TAG:-latest}
    volumes:
      - yii2-app-data:/var/www/basic
    environment:
      - YII_DEBUG=false
      - YII_ENV=prod
      - COOKIE_VALIDATION_KEY=randomkey123456789 # Should be changed to a secure random string
    networks:
      - yii2-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/ping"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  yii2-network:
    driver: overlay

volumes:
  yii2-app-data:
