version: '3.8'
services:
  app:
    image: ${DOCKER_USERNAME:-yourname}/yii2-app:${TAG:-latest}
    volumes:
      - yii2-app-code:/var/www/basic
      - yii2-app-runtime:/var/www/basic/runtime
      - yii2-app-assets:/var/www/basic/web/assets
    ports:
      - "9000:9000"  # Expose PHP-FPM port to host for NGINX
    environment:
      - YII_ENV=${YII_ENV:-prod}
      - YII_DEBUG=${YII_DEBUG:-false}
      - DB_HOST=db
      - DB_NAME=yii2db
      - DB_USER=yii2user
      - DB_PASSWORD=yii2password
    networks:
      - yii2-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/ping"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.0
    volumes:
      - yii2-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=yii2db
      - MYSQL_USER=yii2user
      - MYSQL_PASSWORD=yii2password
    networks:
      - yii2-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  yii2-network:
    driver: overlay

volumes:
  yii2-db-data:
  yii2-app-code:
  yii2-app-runtime:
  yii2-app-assets:
