---
# roles/swarm/tasks/main.yml
- name: Check if swarm is initialized
  command: docker info
  register: docker_info
  changed_when: false

- name: Initialize Docker Swarm
  command: docker swarm init --advertise-addr={{ ansible_default_ipv4.address }}
  when: "docker_info.stdout.find('Swarm: active') == -1"
  register: swarm_init
  
- name: Show swarm init output
  debug:
    var: swarm_init.stdout_lines
  when: swarm_init.changed

- name: Get join token for workers
  command: docker swarm join-token -q worker
  register: worker_token
  when: swarm_init.changed
  changed_when: false

- name: Save worker token
  copy:
    content: "{{ worker_token.stdout }}"
    dest: /root/worker-token
    mode: '0600'
  when: swarm_init.changed

- name: Create Docker network for the application
  command: docker network create --driver overlay yii2-network
  ignore_errors: yes