---
- name: Setup Yii2 Application Environment
  hosts: ec2
  become: yes
  vars:
    app_dir: /opt/{{ app_name }}
    docker_compose_version: "2.17.3"
    github_repo: https://github.com/yourusername/yii2-devops-assessment.git

  roles:
    - common
    - docker
    - nginx
    - swarm

  post_tasks:
    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        
    - name: Clone application repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_dir }}"
        version: main
        
    - name: Deploy the stack
      command: "docker stack deploy -c {{ app_dir }}/docker-compose.yml {{ app_name }}"
      args:
        chdir: "{{ app_dir }}"
      register: stack_deploy
      
    - name: Show deployment result
      debug:
        var: stack_deploy.stdout_lines