name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest,${{ secrets.DOCKER_USERNAME }}/yii2-app:${{ github.sha }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # - name: Deploy to production
      #   run: |
      #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd /opt/yii2-app && \
      #     git pull && \
      #     docker service update --image ${{ secrets.DOCKER_USERNAME }}/yii2-app:${{ github.sha }} yii2-app_app"

      - name: Deploy to production
  	    run: |
    	    ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /opt/yii2-app && \
    	    docker service update --image ${{ secrets.DOCKER_USERNAME }}/yii2-app:${{ github.sha }} yii2-app_app || \
          (cd /opt && docker stack deploy -c /home/${{ secrets.SSH_USER }}/docker-compose.yml yii2-app)"

      - name: Check deployment status
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker service ls && docker service ps yii2-app_app"
